### PR TITLE
Removed version tag of protobuf

### PR DESCRIPTION
**Pull request by jdent23**
Seeing if packages build first

### CODE REVIEW

**Review by arthurp — COMMENTED** [review]
Are you sure this is safe? Would it be better to change this to `protobug >={{ libprotobuf }}`, so that newer protobuf are supported but older are not?

**Comment by jdent23** [comment]
> Are you sure this is safe? Would it be better to change this to `protobug >={{ libprotobuf }}`, so that newer protobuf are supported but older are not?

Good point. Updated to reflect this.

**Comment by jdent23** [comment]
@arthurp first off, I've had to limit setuptools to build pytorch at all
`- setuptools <=58.2.0 py{{ python[0] }}{{ python[2] }}*`
This works and I've uploaded packages under the test label for Pytorch 1.10

Secondly, removing the upper bound from protobuf causes an error that I have no way around. Could you please take a look? Here's the full log output from building, the error is quite long.
https://gist.github.com/jdent23/1d26833917d22689ee57f3fc3a833cfe

**Comment by arthurp** [comment]
The error seems to be due to having different versions of protobuf used to generate the stubs and for the actual C/C++ library. Is the protobuf wrapper source pregenerated or something? Do you need to force a regeneration during build to make it support our version of protobuf?

**Pull request closed without merging**
